package github.ax.meeting.entities;

//部门实体
public class Department {

    private Integer deptId;


    private String deptName;


    private String deptPhone;


    private String deptNo;


    private String deptPassword;


    public String getDeptPassword() {
        return deptPassword;
    }

    public void setDeptPassword(String deptPassword) {
        this.deptPassword = deptPassword;
    }


    public Integer getDeptId() {
        return deptId;
    }


    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }


    public String getDeptName() {
        return deptName;
    }


    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }


    public String getDeptPhone() {
        return deptPhone;
    }


    public void setDeptPhone(String deptPhone) {
        this.deptPhone = deptPhone == null ? null : deptPhone.trim();
    }


    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_no
     *
     * @param deptNo the value for department.dept_no
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    public Department() {
    }

    public Department(String deptName, String deptPhone, String deptNo ,String deptPassword) {
        this.deptName = deptName;
        this.deptPhone = deptPhone;
        this.deptNo = deptNo;
        this.deptPassword = deptPassword;
    }
}