global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ax-meeting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 注意IP换为你的应用IP:Port
      - targets: [ 'axmeetingroom:8080' ]